---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: windrose
  name: windrose
  labels:
    app: windrose
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: windrose
  template:
    metadata:
      labels:
        app: windrose
    spec:
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: windrose
          image: indifferentbroccoli/windrose-server-docker:latest
          securityContext:
            privileged: true
            runAsUser: 0
          resources:
            limits:
              memory: "6Gi"
            requests:
              memory: "4Gi"
          envFrom:
            - secretRef:
                name: windrose-secret
            - configMapRef:
                name: windrose-config
            - configMapRef:
                name: windrose-local-config
          env:
            - name: WINE_NET_STRIP_IPv6
              value: "1"
            - name: USER_SELECTED_REGION
              value: "EU"
            - name: USE_DIRECT_CONNECTION
              value: "true"
            - name: DIRECT_CONNECTION_SERVER_PORT
              value: "7777"
            - name: SERVER_PORT
              value: "7777"
            - name: QUERY_PORT
              value: "7778"
            - name: STEAM_QUERY_PORT
              value: "27015"
          ports:
            - name: game-port
              containerPort: 7777
              protocol: UDP
            - name: query-port
              containerPort: 7778
              protocol: UDP
            - name: steam-query
              containerPort: 27015
              protocol: UDP
          volumeMounts:
            - name: server-files
              mountPath: /home/steam/server-files
      volumes:
        - name: server-files
          persistentVolumeClaim:
            claimName: windrose-pvc
