apiVersion: v1
kind: ConfigMap
metadata:
  name: windrose-config
  namespace: windrose
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  SERVER_NAME: "Morgurth's Pirate Archipelago"
  MAX_PLAYERS: "2"
  UPDATE_ON_START: "true"