apiVersion: v1
kind: Service
metadata:
  name: windrose-lan
  namespace: windrose
spec:
  type: ClusterIP
  selector:
    app: windrose
  ports:
  - name: game-udp
    protocol: UDP
    port: 7777
  - name: query-udp
    protocol: UDP
    port: 7778