---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windrose-pvc
  namespace: windrose
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 35Gi # Adjust size based on your server needs