apiVersion: v1
kind: Service
metadata:
  name: windrose-lan
  namespace: windrose
spec:
  type: NodePort
  selector:
    app: windrose
  ports:
  - name: game-udp
    protocol: UDP
    port: 7777
    nodePort: 30777