resources:
- ../../../../components/certificates/base

patches:
  - patch: |
      - op: replace
        path: /spec/dnsNames/0
        value: "*.apps.morgurth.com"
      - op: replace
        path: /spec/commonName
        value: "*.apps.morgurth.com"
    target:
      kind: Certificate
      name: openshift-wildcard
