apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    io.kompose.service: blinko-website
  name: blinko-website
  namespace: blinko
spec:
  ports:
    - name: "blinko"
      port: 80
      targetPort: 1111
  selector:
    io.kompose.service: blinko-website