apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    io.kompose.service: postgres-claim0
  name: postgres-claim0
  namespace: blinko
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi