---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundryvtt-data-pv-claim
  namespace: foundryvtt
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40G