---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: foundryvtt
  name: foundryvtt
  labels:
    app: foundryvtt
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foundryvtt
  template:
    metadata:
      labels:
        app: foundryvtt
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: foundryvtt-web
          #image: mbround18/foundryvtt-docker:latest
          image: felddy/foundryvtt:13
          env:
            #- name: APPLICATION_HOST
            - name: FOUNDRY_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: foundryvtt-env
                  key: FOUNDRY_HOSTNAME
            - name: FOUNDRY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: foundryvtt-env
                  key: FOUNDRY_USERNAME
            - name: FOUNDRY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: foundryvtt-env
                  key: FOUNDRY_PASSWORD
            - name: FOUNDRY_PROXY_SSL
              value: "true"
            - name: CONTAINER_PRESERVE_CONFIG
              value: "true"
            #- name: APPLICATION_PORT
            #  value: "4444"
            #- name: SSL_PROXY
            #  value: "true"
          ports:
            - name: web
              containerPort: 30000
          volumeMounts:
            - name: foundryvtt-data-persistent-storage
              mountPath: /data
      volumes:
        - name: foundryvtt-data-persistent-storage
          persistentVolumeClaim:
            claimName: foundryvtt-data-pv-claim