apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    argocd.argoproj.io/sync-wave: '5'
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: morgurth@gmail.com
    # This key doesn't exist, cert-manager creates it
    profile: tlsserver
    privateKeySecretRef: 
      name: letsencrypt-zetatech
    solvers:
    - dns01:
        cloudDNS:
          project: graphite-space-283919
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json