apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    argocd.argoproj.io/sync-wave: '5'
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: morgurth@gmail.com
    # This key doesn't exist, cert-manager creates it
    profile: tlsserver
    privateKeySecretRef: 
      name: letsencrypt-zetatech
    solvers:
    - http01:
        ingress:
          name: 
